### ISSUE TITLE
A few questions ...

### ISSUE THREAD

**Issue by niahoo** [flauwekeul/honeycomb#1]
Hi !

I'm playing with your example to see if it could work for a video game. I work with React but other implementations lack of customisation or just does not work.

I'm trying to implement a React view for a video game, so I have a few questions :

First, I make a rectangle map. I may change later but it fits best to a PC screen. I would like to use the “even-q” vertical layout from Red Blob, i.e. the top left angle is round and not sharp ; it feels less sharp to the eye. Is it possible to configure the grid in such a way ?

Then, I would like to draw an isometric map, so is it possible to configure a different radius for the height and the width of the hexagons ?

Thanks !

**Comment by flauwekeul** [comment]
Hey there!

Thanks for using my library (especially in its state of "hobby project") and thanks even more for opening an issue! I need feedback from people other than myself to keep improving this repo 🙃

It is possible to render a grid in the "even-q" configuration! You can use the [`direction` parameter](https://github.com/flauwekeul/honeycomb#gridrectangle) of the `rectangle` method, like so:

```js
grid.rectangle({
    width: 4,
    height: 4,
    direction: 'NW' // assuming a flat orientation
})
```

I think the API (and/or documentation) can be improved for this...but I haven't yet found a better way. Please let me know if you have any ideas.

It's not yet possible to create isometric hexes, but I've added the feature on [the backlog](https://github.com/flauwekeul/honeycomb#features) (nr. 8) some time ago. I think I can find the time to start working on it this weekend.

**Comment by niahoo** [comment]
Hi, 
Thank you very much !

I tried with 'NW' but the map seems flipped and is displayed outside of the screen (above it seems because I see the last row). I'll check if it is a CSS issue.

For the isometric, it doesn't urge if you have better to do this weekend ! I'm currently working on generating realistic maps of islands : coastline, mountains, biomes, etc. Top-down view is OK :)

Do you know a way to generate random hex coordinates that are guaranteed to be on the rectangle ? (Cube-axis theory is hard !)

Generating all the map is very costly, so I generate only the player-visible tiles. Do you think that putting all the hexagons as `<g />` elements inside a single `<svg />` could perform better on viewBox animation ?

Thank you very much :+1:

**Comment by flauwekeul** [comment]
It's not a CSS issue, it's how it's supposed to work. NW means the grid is generated in the North West wind direction, starting from the origin hex. The directions are always relative to the origin hex.

I've been thinking about map generation too. You might want to look into perlin noise ([The Coding Train](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bgPNQAdxQZpJuJCjeOr7VD) has several videos about this that took me from "huh?🤔" to "aha!🤓".

To guarantee that a random hex is in view, the easiest is to make that hex the origin of the grid...

I have no experience with viewBox animation, so I have no idea...

**Comment by niahoo** [comment]
Ok ! Thanks for the support ! 

Yeah I'm playing with perlin/simplex, it's fun !
