### ISSUE TITLE
Types not working on import

### ISSUE THREAD

**Issue by SevYote** [flauwekeul/honeycomb#103]
Heya, ran into some issues trying out honeycomb-grid where imports didn't seem to be working right, which ultimately lead me to [this thread](https://github.com/microsoft/TypeScript/issues/52363).

I used [patch-package](https://github.com/ds300/patch-package) to patch `honeycomb-grid@4.1.1` as shown in the diff below. That got me going, but I'm not sure if that's actually the proper / ideal way to do it. Hopefully it gets you down the right path to a fix, though. [This site](https://arethetypeswrong.github.io/?p=honeycomb-grid%404.1.1) from that thread gives some more info.

```diff
diff --git a/node_modules/honeycomb-grid/package.json b/node_modules/honeycomb-grid/package.json
index 5f36957..c0f71dd 100644
--- a/node_modules/honeycomb-grid/package.json
+++ b/node_modules/honeycomb-grid/package.json
@@ -8,7 +8,10 @@
   "types": "dist/index.d.ts",
   "exports": {
     ".": {
-      "import": "./dist/honeycomb-grid.mjs",
+      "import": {
+        "default": "./dist/honeycomb-grid.mjs",
+        "types": "./dist/index.d.ts"
+      },
       "require": "./dist/honeycomb-grid.umd.js"
     }
   },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by flauwekeul** [comment]
Thanks. I'll look into it later.

**Comment by SIGSTACKFAULT** [comment]
just deleting the `import` block also fixed it for me

**Comment by SIGSTACKFAULT** [comment]
upgrading to TS5 fixed it for me, but I couldn't repro the problem at all in a blank project so /shrug

**Comment by SIGSTACKFAULT** [comment]
adding `"resolvePackageJsonExports": false` to my tsconfig fixed it for me

[ts docs](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports)

**Comment by flauwekeul** [comment]
Sorry for the late fix 😬

**Comment by Altrue** [comment]
Unfortunately this is not fixed @flauwekeul, the package.json references a file located at "./dist/index.d.ts" but the file is actually located at "./src/dist/index.d.ts"

Sorry haha ;D

**Comment by flauwekeul** [comment]
Ugh 😒 I should've tested it. Trying to fix it now.

**Comment by SIGSTACKFAULT** [comment]
<3
