### ISSUE TITLE
Generating a Diamond shaped grid (Isometric requirement)

### ISSUE THREAD

**Issue by arvalaan** [flauwekeul/honeycomb#104]
Interlacing a grid with various chunks in an isometric view causes tiles to overlap each other. This is prevented when we are able to create a diamond shaped grid instead of a squared grid.

Examples of issues being caused when interlacing as is:

![image](https://github.com/flauwekeul/honeycomb/assets/9444629/564bb3d2-470b-4681-9afa-a4117a9de2e1)

Examples of interlacing with a diamond shaped grid:

![image](https://github.com/flauwekeul/honeycomb/assets/9444629/303d18f9-39f5-44db-953e-5601a2e38f5c)

**Comment by flauwekeul** [comment]
Hi. Thanks for opening this issue. It's already possible to create diamond-shaped grids by using the `rectangle()` traverser. See https://abbekeultjes.nl/honeycomb/guide/traversing-grids.html#rectangle and scroll down a bit for the "Warning" block. Does this help?

What do you mean with "interlacing" and how are rectangular grids causing issues? And how are diamond grids fixing these issues?
