### ISSUE TITLE
Grid constructor typing with custom Hex class

### ISSUE THREAD

**Issue by namiwang** [flauwekeul/honeycomb#106]
`new Grid()` always has a type of `Grid<Hex>`, even with a custom Hex class.

A workaround is `new Grid(CustomHex, spiralTraverser) as unknown as Grid<CustomHex>`

**Comment by flauwekeul** [comment]
I see it's broken when just calling `defineHex()` and not using the `class` keyword.
```ts
const CustomHex = defineHex()
const grid = new Grid(CustomHex)
//    ^ Grid<Hex>
```

This has the correct type:
```ts
class CustomHex extends defineHex() {}
const grid = new Grid(CustomHex)
//    ^ Grid<CustomHex>
```

I see I'll fix this. Thanks for opening the issue.

**Comment by flauwekeul** [comment]
With this code:
```ts
const CustomHex = defineHex()
const grid = new Grid(CustomHex)
//    ^ Grid<Hex>
```
I don't see how it's possible to make `grid` have the type `Grid<CustomHex>` (except for what you already mentioned: ` as unknown as Grid<CustomHex>`).

So, unless there are other scenarios where you expect `Grid<CustomHex>` but get `Grid<Hex>` as a type, this seems a non-issue.

**Comment by namiwang** [comment]
I'm indeed using a custom class like this

```
export default class CDHex extends Hex { ... }
const spiralTraverser = spiral( ... )
const grid = new Grid(CustomHex, spiralTraverser)
      ^ Grid<Hex> by default
```

And I just found that the correct way to infer the type is to add typings to `spiral`

```
export default class CustomHex extends Hex { ... }
const spiralTraverser = spiral<CustomHex>( ... )
const grid = new Grid<CustomHex>(CustomHex, spiralTraverser)
      ^ Grid<CustomHex>
```

So yeah, I think there's no issue here. Thanks for the details.
