### ISSUE TITLE
center method is not working

### ISSUE THREAD

**Issue by shallwefootball** [flauwekeul/honeycomb#11]
I want to know the center point of each hexagon, but only one hexagon center point is output.

Let's look at the code below.

```
const Hex = Honeycomb.extendHex({size: 11})
const Grid = Honeycomb.defineGrid(Hex)
Grid.hexagon({radius: 15}).forEach(hex => {
  console.log(hex.toPoint()); // each hexagon points..
  console.log(hex.center()); // just one hexagon points..
});
```

Am I misunderstanding?

**Comment by shallwefootball** [comment]
I think it is because of below.

https://github.com/flauwekeul/honeycomb/blob/4f57685051742d52875af967edd4c402ce19815c/src/hex/prototype.js#L252

Then, do you not know the center of each hexagon?

**Comment by flauwekeul** [comment]
I can imagine you expect a hexagon's `center()` method returns the center position of the hexagon you called it on relative to `Hex(0, 0)`. But unfortunately `Hex#center()` returns the same point for all hexagons in the grid. I have an item on my [backlog](https://github.com/flauwekeul/honeycomb#-features) (see item 4) to fix this, but I haven't come around to it...

You can get around it by adding the hex's point, like so:

```js
const Hex = Honeycomb.extendHex({size: 11})
const Grid = Honeycomb.defineGrid(Hex)

Grid.hexagon({radius: 15}).forEach(hex => {
  console.log(hex.center().add(hex.toPoint()));
});
```
