### ISSUE TITLE
Offset Coordinates produce a reversed grid

### ISSUE THREAD

**Issue by altarrok** [flauwekeul/honeycomb#112]
When using the offset coordinates, the grid is mirrored (0 should be leftmost, but it is rightmost column index)

Here is the sandbox that produces it:

https://codesandbox.io/s/three-fiber-hex-grid-forked-ksr9ff?file=/src/App.js

![image](https://github.com/flauwekeul/honeycomb/assets/45828884/2bdd7356-0059-4f22-b6c6-6ec6bd1864fa)
_The grid rendered, and each hex has the <col, row> numbers on at the top of them_

![image](https://github.com/flauwekeul/honeycomb/assets/45828884/e6ebc4f4-226f-45d9-8834-f0f2ff3d4aa9)
_This is the grid from redblobgames, with <col, row> numbers on them. Note that the leftmost highlighted hex has col = 0_

Wondering if this is an issue on my end, I checked the center positions of the leftmost and the rightmost hex', in the middle row:
<0, 3> (expected to be leftmost, but rightmost in the result): {x: 5, y: 1.5}
<4, 3> (expected to be rightmost, but leftmost in the result): {x: -1.9282032302755086, y: 1.5}

So as one can see, the center positions are incorrect, therefore this is the result of the behavior of the honeycomb library. I checked the API thoroughly, but couldn't find a configuration that would fix this, nor any other previous issues mentioning the problem. This is important for my use case, if you would like to discuss more about the problem please feel free to leave a comment, thank you.

**If you run into the same problem and looking for a hack; multiply center.x by -1**

**Comment by flauwekeul** [comment]
Hi. I'm quite sure this is a problem on your end 😅 Haven't got the time yet to investigate your code though.

If you implement one of the [rendering examples](https://abbekeultjes.nl/honeycomb/guide/rendering.html) and render or log the offset coordinates, they should be on the expected hexes.

**Comment by flauwekeul** [comment]
This is what I see when I open your code sandbox (Chrome 119):

![Screenshot 2023-11-18 at 20 49 21](https://github.com/flauwekeul/honeycomb/assets/1648809/5d3f1d01-b2bb-4cfa-a20d-5f9820d9d52d)

Maybe I see a different version or you managed to fix it or something? Please let me know when you have code that reproduces the problem.

**Comment by altarrok** [comment]
@flauwekeul sorry, I applied my hack fix to it, so it was in the correct way because of the reversed x, if you check now, it should be clear that the center.x out of the library is wrong.

**Comment by flauwekeul** [comment]
I think I figured it out. The problem is `hex.center` is a rather... confusing property because it always returns the position relative to the _top left corner_ of the hex with coordinates `0, 0`. So you set your origin to `{ x: 5, y: 5 }`, but `hex.center` ignores this and just does this:

```ts
  // todo: add to docs that this always returns a point relative to Hex(0, 0)'s top left corner!
  // todo: probably deprecate this, see: https://github.com/flauwekeul/honeycomb/discussions/95#discussioncomment-5158862
  get center(): Point {
    const { width, height, x, y } = this
    return { x: width / 2 - x, y: height / 2 - y }
  }
```

Copied that from the [source code](https://github.com/flauwekeul/honeycomb/blob/master/src/hex/hex.ts#L27-L32), including the comment.

If you want the actual origin point of each hex (relative to hex with coordinates `0, 0`), you can just use `hex.x` and `hex.y`. If you change line 133 like so:

```diff
-  const { x: originX, y: originY } = hex.center;
+  const { x: originX, y: originY } = hex;
```

It should all work as you expect.

I'll deprecate `hex.center` (should've done that earlier...). Sorry for the inconvenience.
