### ISSUE TITLE
Spiral Traverser not working as expected

### ISSUE THREAD

**Issue by exp111** [flauwekeul/honeycomb#117]
**Describe the bug**
The spiral traverser does not work as expected.
Lets take the example from [the docs](https://abbekeultjes.nl/honeycomb/guide/traversing-grids.html#what-is-a-traverser):
```ts
const Hex = defineHex({ dimensions: 30 });
const grid = new Grid(Hex, rectangle({
  width: 5,
  height: 5
}));
const spiralTraverser = spiral(
  {
    start: [0, 2],
    radius: 1
  });

for (let h of grid.traverse(spiralTraverser)) {
  console.log(`col: ${h.col}, row: ${h.row}`);
}
```
I'd expect it to print out the hexes in this order:
- 1,1
- 1,2
- 0,3
- -1,3
- -1,2
- 0,1

However it prints out:
```
col: 1, row: 2
col: 1, row: 1
col: 2, row: 2
col: 1, row: 3
col: 0, row: 3
col: 0, row: 2 
col: 0, row: 1
```
Meaning it made a spiral with its center at 1,2.
If I start it at 1,2 it does a spiral at 2,2.
The offset isnt always one as on a 10x10 grid with a start at 1,7 it will do a spiral at 4,7

**Environment (please complete the following information):**
 - Honeycomb 4.1.5
 - Angular 18.0.0
 - node.js 22.4.0
 - Firefox 128.0

**Screenshots**
0,2 to 1,2 offset visualized:
![grafik](https://github.com/user-attachments/assets/519a462e-406d-427c-8236-c94172a10e58)

1,7 to 4,7 visualized:
![grafik](https://github.com/user-attachments/assets/9eb65314-6625-4b6d-b7b8-f60e35502ed2)

**Comment by exp111** [comment]
Okay yea I got it. The HexCoordiantes `[0,2]` aren't `{col: 0, row: 2}` but `{q: 0, r: 2}`.

**Comment by flauwekeul** [comment]
Sorry for answering so late, but good that you figured it out yourself 👍 

Pretty textures btw.
