### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by PiotrZakrzewski** [flauwekeul/honeycomb#12]
Hi!

I just wanted to say thank you for publishing this lib! I am using it for a tiny game prototype I am playing around with now. Do you have any roadmap or known bugs or some features in mind? Mind be useful to drop them into some easy to start on issues so that someone (maybe me) can pick up and make this lib's bus factor higher.

cheers!

**Comment by flauwekeul** [comment]
Hi,

Sorry for my very late reply, I had other stuff on my mind.

At the end of the readme there's a [backlog](https://github.com/flauwekeul/honeycomb#backlog). As you can see there aren't any known bugs and I have quite a few feature ideas. A lot of them end with a question mark meaning I'm not sure if and how I want that feature. I've started with some ideas, but they proved a lot of work and/or didn't turn out the way I wanted and I've kinda lost interest...

So I'm afraid there aren't really any easy things you can help out with. I appreciate the gesture though 👍 Of course, if you have any feature requests, let me know. If you're serious in helping out, I'll add some guidelines for contributing.

**Comment by PiotrZakrzewski** [comment]
Hi!
No problem. In fact I would like to contribute a bit, I find this lib very useful and it would be a pity if it fell too much behind because then someone else will reimplement it again to much lost time for everyone.
One issue I found is that the package published on npm is not transpiled to es5, that prevents it from being used in some popular webpack setups like the shipped with create-react-app.
Would you consider publishing next version transpiled to es5?

**Comment by flauwekeul** [comment]
As @hankolsen mentioned, I can't transpile the code to es5 because I need to extend `Array`. This is one of the few things that can't be polyfilled completely.

When I wrote the code that extends `Array` I also looked at other ways to get the API I intended (using a plain object and using a proxy). At the time I found the API more important than not being able to transpile to es5 completely.

**Comment by PiotrZakrzewski** [comment]
Ok! Clear. 
I went trough the backlog, I will see if there is anything I can pick up.
cheers!
