### ISSUE TITLE
Problem with downloading

### ISSUE THREAD

**Issue by BlueskyFR** [flauwekeul/honeycomb#13]
Hi!

You forget to add a download option for those who want to use it in browser.
I mean a .min version, I don't want to have all the source in my dir you know :)

Can you help me with that?

Thanks !

**Comment by hankolsen** [comment]
Sorry if I'm mansplaining, but I think what @BlueskyFR  means is if you don't use npm but rather a plain old html page with javascript includes, you'd like to just download a .min.js and include that in your html file.

**Comment by BlueskyFR** [comment]
You're right @hankolsen !

**Comment by flauwekeul** [comment]
Right. You can use unpkg.com for that: https://unpkg.com/honeycomb-grid/dist/honeycomb.min.js. I'll add it to the docs as well 👍
