### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by ktiedt** [flauwekeul/honeycomb#14]
In several closed issues you reference an examples folder, they seem to have vanished though?

I was hoping to find an example of rendering text inside a hex, as I want to print coordinates out to compare the various rendering options. In addition to that, the ability to stroke the edges custom colors/weights?

This is by far the simplest looking hex generator I've seen in awhile, rot.js was my previous experience but it was pretty difficult to gain an understanding of... 

Keep up the awesome work, and hopefully I'll have some contributions as well once I get things nailed down :D

**Comment by flauwekeul** [comment]
I had an examples folder, but I removed it in favour of documentation with [examples](https://github.com/flauwekeul/honeycomb#rendering). Those examples probably won't answer your question though. Honeycomb is completely viewless; lacking any functionality for rendering. It seems to me your question isn't about honeycomb, but about whatever rendering engine you're using.

I have an example on [jsfiddle.net](https://jsfiddle.net/Flauwekeul/arxo1vqo/) where each hex shows its coordinates. It uses SVG for rendering and you might want to use canvas. I have an [example with PIXI.js](https://jsfiddle.net/Flauwekeul/qmfgey44/) you might want to play around with.

Let me know if you need more help.

And thanks a lot for the kind words! I'm planning to rewrite the project in Typescript and I expect to make some breaking changes too. Hopefully I'm able to release v2 in a few months.

**Comment by ktiedt** [comment]
Ahh thanks, I hadn't thought to consider the docs replaced the examples. I had looked at the PIXI jsfiddle but missed that SVG coordinates one.

And you would be right, I was hoping to use canvas over SVG so PIXI was what I was looking at for rendering. I think between these 2 I can piece together an answer for each of my questions now :D

Thanks!

**Comment by flauwekeul** [comment]
Glad to help 👍
