### ISSUE TITLE
[Feature Request] Add `proto` to `Hex` instead of using `Hex().__proto__`

### ISSUE THREAD

**Issue by grandsong** [flauwekeul/honeycomb#19]
`Hex` created via `Honeycomb.extendHex()` is not a class.
As a result, when we need to access properties of the hex prototype (like calculating the size of the SVG element of the grid), we have to write `Hex().__proto__`.

It is OK, but not good enough.

Since it is feasible and not uncommon in practice to make a function have its properties (when they are logically most closely related with the function), why not provide us with something like `Hex.proto`?

---

I know it is not a big deal, but bad code smells even when it is small. :nose:

**Comment by flauwekeul** [comment]
Would `Object.getPrototypeOf(Hex())` work for you?

I'm rewriting the library in Typescript and then `Hex` *will* be a class and you can just write `Hex.prototype`.

**Comment by grandsong** [comment]
`Object.getPrototypeOf(Hex())` is effectively the same as `Hex().__proto__` but even much uglier...

It will be greate to make 'Hex' a class instead of a factory.
