### ISSUE TITLE
Don't

### ISSUE THREAD

**Issue by thipages** [flauwekeul/honeycomb#27]
rewrite in typescript ;-)

Have a look first at this paper [JS is not worse than ...](https://itnext.io/js-is-not-worse-than-84a5fca0e87d)

Great library!

**Comment by flauwekeul** [comment]
I started the rewrite, but didn't finish. Yet. But I probably never finish it 😅

After about 2 years of writing typescript my opinion on the language went from _awful_ to _awesome_ and now I've settled on: it's okay-ish. [This post](https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b) of Eric Elliott made my opinion go from _okay_ to _okay-ish_.

Thanks for using the library, let me know if you miss any features.

**Comment by thipages** [comment]
Eric Eliott post is good also!
So lets try to focus more on the functional part of JS as u wrote a line after. Pleased to read u.
