### ISSUE TITLE
Type definitions are broken with latest TypeScript version (starting from 3.0.0)

### ISSUE THREAD

**Issue by dfernandeza** [flauwekeul/honeycomb#28]
Upgrading TypeScript from 3.2.4 to 3.3.3 is causing the following problems: 

**node_modules/honeycomb-grid/dist/honeycomb.d.ts:1:44 - error TS2744: Type parameter defaults can only reference previously declared type parameters.**

```declare function defineGrid<T = HexFactory<T>>(Hex?: HexFactory<T>): GridFactory<Hex<T>>```

**node_modules/honeycomb-grid/dist/honeycomb.d.ts:36:27 - error TS2744: Type parameter defaults can only reference previously declared type parameters.**

```export class Grid<T = Hex<T>> extends Array<T> {```

For more information please check [this issue](https://github.com/Microsoft/TypeScript/issues/29803) in the TypeScript repository.

Thanks

**Comment by flauwekeul** [comment]
Thanks! I'll try to look into it in the coming days.

**Comment by flauwekeul** [comment]
I've made pre-release v1.4.4-0, because I'm not entirely sure all types still work. Could you test it and let me know if you run into any issues? Thanks 👍

**Comment by dfernandeza** [comment]
It works perfectly 👏

**Comment by flauwekeul** [comment]
Great :smiley: let me know if you miss any features or find more bugs or whatever.

**Comment by dfernandeza** [comment]
I will for sure. Thanks again

**Comment by Awia00** [comment]
Will you release version 1.4.4 to npm? Thanks in advance

**Comment by flauwekeul** [comment]
Thanks for reminding me 😅 I've just released 1.4.4

**Comment by Awia00** [comment]
Thanks 👍

**Comment by hagm1986** [comment]
error TS2744: Type parameter defaults can only reference previously declared type parameters.
