### ISSUE TITLE
SVG.js example doesn't work with latest version of SVG.js

### ISSUE THREAD

**Issue by misbach** [flauwekeul/honeycomb#29]
The SVG.js code example in the readme.md doesn't compile with the SVG.js version 3.x It complains about `draw.symbol()`

**Comment by flauwekeul** [comment]
Thanks for heads-up 👍 I don't know how to fix it though 😕 According to the [docs](https://svgjs.com/docs/3.0/parents/#svg-symbol) it should work. I can't find anything related to symbols in the [changelog](https://github.com/svgdotjs/svg.js/blob/master/CHANGELOG.md) either...

I've asked around in their gitter.

**Comment by misbach** [comment]
Glad to know I'm not the only one to struggle to fix it. I wanted to give you a pull request rather than just complain about it, but I didn't see how to fix it either.

**Comment by flauwekeul** [comment]
Fixed in #53
