### ISSUE TITLE
Hex#corners not working

### ISSUE THREAD

**Issue by luetkemj** [flauwekeul/honeycomb#3]
Thanks for making this lib - I'm hoping to make heavy use of it in a hobby project.

Having difficulty with the following bit of code, not sure if bug or user error:

```
const grid = Grid({
  size: 20,
  orientation: HEX_ORIENTATIONS.FLAT,
});

const hexArray = grid.rectangle({
  width: 2,
  height: 2,
  direction: 1,
});

hexArray.forEach(hex => console.log( grid.Hex(hex).corners()) );
```

**Expected behavior**: console should log 4 arrays of corners, each with a unique set of coords

**Actual behavior**: console logs 4 arrays of corners, _each with the same set of coords_

**Comment by flauwekeul** [comment]
Thanks for using honeycomb 😎

`grid.rectangle()` returns an array of hexes, so you can just call `corners()` on each hex:

```js
hexArray.forEach(hex => console.log( hex.corners() );
```

However, each `corners` array will still consist of the same coordinates. This is because the corners are relative to the hex.

To get the absolute corners points (relative to the grid), you should add each hex's point, like so:

```js
hexArray.forEach(hex => console.log(hex.corners().map(corner => hex.toPoint().add(corner))) );
```

That's quite a lot of code... Why do you need the absolute corner points?

**Comment by luetkemj** [comment]
Interesting...

The reason I need absolute corner points (and I suppose I may be going about this the wrong way) is   to render a hexmap with Pixi.js. My understanding on how best to do that is with a drawHex function that will use the corner coords for each hex to draw itself.

I ran a test using your prescribed method to get corners with honeycomb and how I had been doing it. To my great surprise honeycomb was far slower. What is the motivation for how you are doing it? Am I just approaching this the wrong way and missing a far simpler and faster approach?

```
import { Grid, HEX_ORIENTATIONS } from 'honeycomb-grid';

const app = new PIXI.Application(800, 600, { antialias: true, resolution: 1 });

document.getElementById('map').appendChild(app.view);

const graphics = new PIXI.Graphics();

const grid = Grid({
  size: 20,
  orientation: HEX_ORIENTATIONS.FLAT,
});

const hexArray = grid.rectangle({
  width: 200,
  height: 200,
  direction: 1,
});

function drawHexagon(hex) {
  graphics.beginFill(0x333333);
  graphics.lineStyle(1, 0xFFFFFF, 1);

  const corners = hex.corners().map(corner => hex.toPoint().add(corner));
  // move to the location of our first hex corner
  graphics.moveTo(corners[0].x, corners[0].y);

  // draw from each corner to the next
  for (let i = 1; i < 6; i += 1) {
    graphics.lineTo(corners[i].x, corners[i].y);
  }

  // connect back to where we started
  graphics.lineTo(corners[0].x, corners[0].y);

  app.stage.addChild(graphics);
}

// OLD METHOD FOR TESTING
function hexCorner(center, size, i) {
  const deg = 60 * i;
  const rad = (Math.PI / 180) * deg;

  return {
    x: center.x + (size * Math.cos(rad)),
    y: center.y + (size * Math.sin(rad)),
  };
}

function drawHexagonOld(center, size) {
  graphics.beginFill(0x333333);
  graphics.lineStyle(1, 0xFFFFFF, 1);

  let point = hexCorner(center, size, 0);
  graphics.moveTo(point.x, point.y);

  for (let i = 1; i < 7; i += 1) {
    point = hexCorner(center, size, i);
    graphics.lineTo(point.x, point.y);
  }
  app.stage.addChild(graphics);
}
// OLD METHOD FOR TESTING


console.time('drawing hexes Old');
hexArray.forEach(hex => drawHexagonOld(grid.hexToPoint(hex), 20)); // 174.385986328125ms
console.timeEnd('drawing hexes Old');


console.time('drawing hexes');
hexArray.forEach(hex => drawHexagon(hex)); // 1212.151123046875ms
console.timeEnd('drawing hexes');
```

**Comment by luetkemj** [comment]
Having had a day to tinker with things I don't believe I was approaching this problem from the right angle. I can use image sprites with hex.toPoint() to place them all. Much simpler. Still curious about this though.

**Comment by flauwekeul** [comment]
pixi.js uses canvas, right? I tried using honeycomb to draw on a canvas some time ago and also found it to be very slow.

I created honeycomb with a component-based type of coding in mind, something that's more suitable for SVG's or other DOM nodes. Canvas rendering is more action-based: your code consists of actions to move a virtual pen around. This might cause the huge difference in performance. I'd prefer honeycomb to be performant when using canvas too, though. I'll put an item on the [backlog](https://github.com/flauwekeul/honeycomb#backlog) to try to figure it out. I'm glad you found a workaround.

Currently, I'm in the middle of a big refactoring. While dogfooding honeycomb, I noticed `Honeycomb.View` isn't very useful, so I'll remove it entirely. Also: `grid.Hex` has a lot of static methods which should just be prototype methods. I'll finish that first, then I'll look into this issue.

Please let me know if you have any more issues or questions!

**Comment by luetkemj** [comment]
Yeah, PIXI is canvas based. I had taken an SVG approach to the map thing I am working but the number of hexes caused the browser to really chug. Pixi seems to help a lot with that- just a huge mental shift for me. 

Let me know if I can do anything to help out. Appreciate you putting this together, much more complete than anything I would have done 👍

**Comment by flauwekeul** [comment]
Some days ago I released v1 of Honeycomb and I've (finally) looked into rendering with PixiJS. I've added [an example](https://github.com/flauwekeul/honeycomb#with-pixijs), including a [JSFiddle](https://jsfiddle.net/Flauwekeul/qmfgey44/). I think it's pretty performant.
