### ISSUE TITLE
Force "odd" or "even"

### ISSUE THREAD

**Issue by khamaileon** [flauwekeul/honeycomb#30]
Grid.rectangle returns "odd" or "even" layouts. Is it possible to force the type of layout ?
https://www.redblobgames.com/grids/hexagons/#coordinates-offset

**Comment by flauwekeul** [comment]
Hi, thanks for your question. The thing you're looking for is the [`offset` property](https://github.com/flauwekeul/honeycomb#offset-1) that you can pass to `extendHex()`.

I've made a [jsfiddle](https://jsfiddle.net/Flauwekeul/36jot1h7/) as an example and I'll add it to the documentation later. Does this answer your question?

**Comment by khamaileon** [comment]
Oh that's exactly what I'm looking for. Thank you very much !!!
