### ISSUE TITLE
[Feature Request] Support Hex weights

### ISSUE THREAD

**Issue by scottyseus** [flauwekeul/honeycomb#33]
It would be sick if this library supported an additional weight property on Hex objects. This would enable functions like Hex.distance and some of the Grid functions to support more use cases.

I noticed [Red Blob's article](https://www.redblobgames.com/grids/hexagons/#pathfinding) mentions 'movement cost', it would be nice if that could be a parameter of the individual Hex objects.

**Comment by flauwekeul** [comment]
It's already possible to add ["custom" properties](https://github.com/flauwekeul/honeycomb/blob/master/README.md#extendhex) to hexes. Could that be a solution?
