### ISSUE TITLE
Field of view-calculation?

### ISSUE THREAD

**Issue by xird** [flauwekeul/honeycomb#35]
Any plans on including FOV-calculation to the library?

https://www.redblobgames.com/grids/hexagons/#field-of-view
https://www.redblobgames.com/articles/visibility/

**Comment by flauwekeul** [comment]
Hi! This is one of those features I wanted to add when people ask about it. I'm planning on finishing the other open issues first and then I'll look into adding FOV :+1:

**Comment by xird** [comment]
Cool, thanks! Do you already have an algorithm in mind? I could use a feature where Honeycomb could tell me if the target hex is partially or fully in view of the source hex. If that turns out to be too complex, even a simpler implementation would be a huge help.

**Comment by flauwekeul** [comment]
You might be able to mimic FOV using https://github.com/flauwekeul/honeycomb#hexesbetween. It returns all hexes between two specified hexes (by "drawing" a straight line between their center points), just like this: https://www.redblobgames.com/grids/hexagons/#line-drawing.

For the partial or fully in view: that's gonna be hard I think. I would need the most left and most right point of the target hex as seen from the start hex. And I doubt if a lot of people need that feature...

**Comment by flauwekeul** [comment]
@xird Did you get what you wanted with the `hexesBetween()` method? Do you still need a more sophisticated FOV that somehow incorporates partially visible hexes? If yes: could you tell me what you need and how you'd expect the API to look?

**Comment by xird** [comment]
I've been working on a coordinate conversion issue, so I haven't had a chance to think about this much yet. For background: I'm working on a turn-based tactical shooter.

The hexesBetween() looks like I can definitely use that to check for line of sight between a shooter and a chosen target; thanks for pointing that out. However, _if_ I want to implement a feature where only things in sight of the player character are rendered on screen, then a purpose-built FOV function would be necessary. The "partial visibility" feature would be useful when the target is partially occluded; That would decrease the chances of hitting the target.

I have a whole heap of work to do before I get to the line-of-sight issues, so I don't have any idea about how the API should work just yet. I'll get back to you when I have a better idea for what I need.

**Comment by flauwekeul** [comment]
Honeycomb's smallest unit is a hex, for your FOV to work you need a smaller unit (pixels). To achieve your accurate FOV I think you need to create your own pixel-based layer, separate from your hex layer. Then you can calculate the FOV in this pixel-based layer and determine whether a character is visible. In other words: I think your request is out of honeycomb's scope, so I'm closing this issue. Let me know if I can help you with other honeycomb-related stuff.

**Comment by xird** [comment]
For the "partial visibility" feature, I agree. For a general full-hex FOV feature, one-hex accuracy would be doable; redblobgames has a demo of that. 

However, since I will probably need the partial visibility, it'll have to be a custom solution in any case.

**Comment by flauwekeul** [comment]
With the `hexesBetween` method it should be fairly easy to know whether a hex is in view or not:
```js
const isHexBHidden = grid.hexesBetween(hexA, hexB).some(hex => hex.blocksView)
```
I don't think it's necessary to add a new method that only does this. I could add it to the docs though.

**Comment by xird** [comment]
Looks like that's the way to go. I thought I remembered redblobgames showing some fancier algorithm for full grid hex FOV detection, but it was just an article about generic 2D FOV calculation (https://www.redblobgames.com/articles/visibility/).
