### ISSUE TITLE
TypeError: grid.neighborsOf is not a function in when used with vm.$set in Vue 

### ISSUE THREAD

**Issue by altunyurt** [flauwekeul/honeycomb#36]
I'm using hc with vue as follows

```js
    mounted() {
        let self = this;

        const Hex = extendHex({
            size: 20,
            orientation: "flat"
        });

        let Grid = defineGrid(Hex);
        let grid = Grid.rectangle({
            width: 25, // value:		number (excluding center hex)
            height: 20,
            start: [0, 0], // value: 	any point
        });

        console.log(1, grid.neighborsOf(Hex(), [1, 10])); // this outputs 1 array[...]
        self.$set(self, "hex", Hex);
        console.log(2, grid.neighborsOf(Hex(), [1, 10])); // this outputs 2 array[...]
        self.$set(self, "grid", grid);
        console.log(3, grid.neighborsOf(Hex(), [1, 10])); // this fails with grid.neighborsOf is not a function 
}
```

Am i doing something wrong here?

**Comment by flauwekeul** [comment]
Unfortunately I don't have any experience with Vue and apparently `self.$set()` alters the prototype of `grid`.

When you pass a different object with a dummy prototype method to `self.$set()` (e.g. `self.$set(self, 'dummy', Object.create({ blah() { console.log('blah') } }))`) and you call the dummy method, do you get the same error? If yes, that could indicate you aren't supposed to pass objects with prototypes.

I think the people on stackoverflow.com can be of more help...

**Comment by altunyurt** [comment]
@flauwekeul thank you for the fast response.

As you mentioned, $set adds reactivity to object, which alters the object, breaking the lookup process. 

Basically ditching reactiveness as below made it work for me, allowing access the grid and hex from anywhere in the component.  
 
```js 
mounted() {
    this.hex = extendHex({...})
    let Grid = defineGrid(this.hex); 
    this.grid = Grid.rectangle({...})
}
```
