### ISSUE TITLE
Set an all grid and add properties to an hex

### ISSUE THREAD

**Issue by Azumix** [flauwekeul/honeycomb#39]
Hello again ;) ,
My goal is to use your tool as a map generator. I have to save that map in a database in order to allow the user to find it back. I thought about saving the coordinates of each hex.
My question is : when I have my array of coordinate after an API call, what is the best way to display back those hex ? 

I got a second question, in my map the hex has more properties. So once again, what is the best way to do that ?

Thanks for your answer.

**Comment by flauwekeul** [comment]
This is very related to #34. I'm hoping to finish #32 today and then I'll start on #34 (and also your issue). I've tried to come up with a temporary solution so you can move on, but I wasn't able to unfortunately.

I'll keep you posted.

**Comment by EmilyenL** [comment]
Indeed I didn't saw it.
My projet must be done for 25th June so I will try to do something. 
I'll keep you update if I find something. :)

**Comment by flauwekeul** [comment]
I managed to come up with an ugly hack that should work:

To stringify a grid:
```js
// grid is a Grid instance
JSON.stringify(grid.map(hex => JSON.stringify(hex)))
```

To deserialize it back to a grid:
```js
// stringifiedGrid is the result from the above code
Grid(JSON.parse(stringifiedGrid).map(hexString => Hex(JSON.parse(hexString))))
```

It should also retain any custom properties your hexes have.

**Comment by EmilyenL** [comment]
Thanks for that. Subsequent question : how to set custom properties to the grid ?

**Comment by flauwekeul** [comment]
I think you should be able to just do `grid.customProperty = 'some value'`. Or do you want to add custom methods when you call `defineGrid()`? Why do you want to add custom properties to the grid?

**Comment by EmilyenL** [comment]
As I saied in my first post the hex grid is used as a map, so basicaly each hex correspond to a case of the map. I need to save the case in order to allow the user to generate the map, do some operation on it, etc. 
I use HoneyComb (beautiful things, thank you very much for it!). 

My idea was to make each hex correspond to a case. To do that I would like to add a reference to the case in the correspondinf hex.

If you have a better idea I take it. :smiley:

**Comment by flauwekeul** [comment]
I thought you wanted to add custom properties to a _grid_ instance, but you seem to want to add custom properties to _hex_ instances. I have some examples of that in the [docs](https://github.com/flauwekeul/honeycomb#extendhex).

**Comment by Azumix** [comment]
Didn't saw it sory. In your exemple, you set a property and a value to it.
Is it possible to add a type (like string) and set its value with setter (and get it with getter) ? 
So, the goal is to add a custom property type then set it.

**Comment by flauwekeul** [comment]
Something like this?
```js
Honeycomb.extendHex({
    setCustom(value) {
        this._custom = value
    },
    getCustom() {
        return this._custom
    }
})
```
Then you can add type checking in those methods. Otherwise I don't see why you wouldn't just use a property.

**Comment by Azumix** [comment]
Yep, that's what I need.
Thank you very much!

**Comment by Azumix** [comment]
Hello, I probably miss something basic but I do not understand where can I set the deserialized string to my  Grid. Can you help my with that ? 
Here is my code :

``` 
  Hex = Honeycomb.extendHex({
    size: 100,
    resource: '',
    caseTypeid: null,
    caseStateId: null,
    indexOfCaseArray: null
  });
  Grid = Honeycomb.defineGrid(this.Hex);
  loop = this.Grid.rectangle({ width: this.sq + 1, height: this.sq + 1 });
  this.Grid(JSON.parse(this.mapUp.mapJsonSeri).map(hexString => this.Hex(JSON.parse(hexString))));
  this.Grid.rectangle({ width: 10, height: 10 }).forEach(hex => {
     const { x, y } = hex.toPoint();
  });
  this.loop = this.Grid.rectangle({ width: this.sq + 1, height: this.sq + 1 });
```

`this.map.mapJsonSeri` contain the good serialization of the grid. Am I doing something wrong ? (I suppose cause it doesn't work)

**Comment by flauwekeul** [comment]
With only this code I don't see anything wrong. But I notice you use a lot of `this`, that could cause some problems. Could you make a [jsfiddle](http://jsfiddle.net) where the problem is reproduced? Or you could replace some `this` with `this.bind(this)` to make sure all contexts check out.

**Comment by Azumix** [comment]
It's a bit hard to make a jsfiddle since I use Angular with a lot of component/services/resovlers etc but I'll try.
The reason why I use a lot of this it's because TSLint is not happy if I don't use it.

**Comment by Azumix** [comment]
I found a solution just need to do : 
```
    this.loop = this.Grid(JSON.parse(this.mapUp.mapJsonSeri).map(hexString => this.Hex(JSON.parse(hexString))));

```

**Comment by flauwekeul** [comment]
I've just released version 3 of Honeycomb which should solve your issue (without hacks). I've updated the docs with examples. Please let me know if you have any more questions/requests.
