### ISSUE TITLE
Examples show Grid#hexagon misuse

### ISSUE THREAD

**Issue by DreadfulDeveloper** [flauwekeul/honeycomb#5]
Grid#hexagon takes an options object, but in the examples it is shown accepting an integer argument grid.hexagon(3).  When called with an integer, Grid#hexagon returns an empty array.

**Comment by flauwekeul** [comment]
Thanks for opening this issue. I'll look into it next week.

**Comment by flauwekeul** [comment]
In a [commit](https://github.com/flauwekeul/honeycomb/commit/1decae52dae8815481f76b2890e0404825900920) I hadn't pushed yet, I've removed everything view related. This also fixes this issue.

Sorry it took so long to properly respond. I had my wedding to organize (and attend 😅) and suffer the ensuing food poisoning :nauseated_face:
