### ISSUE TITLE
Question, what's the difference between translate(x,y) and move(x,y)?

### ISSUE THREAD

**Issue by lpnueg4** [flauwekeul/honeycomb#62]
Hi everyone, could you tell me, what's the difference between translate(x,y) and move(x,y)?

**Comment by flauwekeul** [comment]
Honeycomb doesn't have a translate() nor a move() function. Do you mean the ones from SVG.js? I think translate is one of the transform methods that will set an `transform="translate(x, y)"` attribute on the element and move will probably alter the element's `x` and `y` attributes directly. Not sure when to use which, probably better to ask in SVG.js's [gitter channel](https://gitter.im/svgdotjs/svg.js) or something.
