### ISSUE TITLE
Error in TS

### ISSUE THREAD

**Issue by Vmalleron** [flauwekeul/honeycomb#8]
`ERROR in node_modules/honeycomb-grid/dist/honeycomb.d.ts(47,32): error TS2304: Cannot find name 'ConcatArray'.`

**Comment by Vmalleron** [comment]
Thank you for your reply! I use the version Version 2.7.2 of typescript






2018-04-11 12:23 GMT+02:00 Abbe Keultjes <notifications@github.com>:

**Comment by flauwekeul** [comment]
The type for `ConcatArray` should be present in your `node_modules/typescript/lib/lib.es5.d.ts`...

As a workaround, you could add the type yourself:

```ts
interface ConcatArray<T> {
    readonly length: number;
    readonly [n: number]: T;
    join(separator?: string): string;
    slice(start?: number, end?: number): T[];
}
```

**Comment by flauwekeul** [comment]
Assuming this issue is solved, I'm gonna close it.

**Comment by Vmalleron** [comment]
Yes it is , sorry i forgot to close the issue.thanks for the help.have a
good day

Le mar. 17 avr. 2018 à 20:35, Abbe Keultjes <notifications@github.com> a
écrit :
