### ISSUE TITLE
bail logic is backwards in traverse()?

### ISSUE THREAD

**Issue by israelidanny** [flauwekeul/honeycomb#84]
https://github.com/flauwekeul/honeycomb/blob/5fb3fd1bd7c6e0755567e6f1d784d46b295efc98/src/grid/grid.ts#L107

It seems to me that right now the intended logic is backwards? If `bail = true` it won't bail, if `bail = false` it will.

**Comment by flauwekeul** [comment]
Good catch. Fixed it in `next`.
