### ISSUE TITLE
What is the logic behind when we use Tile and when we use Tile.prototype?

### ISSUE THREAD

**Issue by israelidanny** [flauwekeul/honeycomb#86]
```
export class Tile extends defineHex({
  orientation: Orientation.POINTY, // pointy orientation
  offset: -1, // odd rows are offset
}) {
  // ...
}
```

When we do `new Grid(Tile...` we just use Tile, but in some places like `distance()` we use `Tile.prototype` which seems to be the legacy approach. Is this by design and I'm missing some logic / motivation? Or is this "technical debt"?

**Comment by flauwekeul** [comment]
It is by design, but I understand the confusion. I could change `distance()` (and other functions that require the prototype) to just accept a `Hex` class/constructor. Then internally, the function can get the `prototype` property. However, the function doesn't _need_ the class/constructor, it needs the prototype. But from a user perspective having to pass `Tile.prototype` may be weird... What do you suggest?

**Comment by israelidanny** [comment]
So now that I'm paying it some second thought. I like that it just needs two quite static things, orientation and offset. I think that using `Tile` everywhere would be a downgrade in testability, developer experience e.t.c

However, passing `prototype` anywhere is quite weird, as well. I think I know where the source of weirdness is, give me a few minutes I'll prepare a minimalistic example.

**Comment by israelidanny** [comment]
Ah, I forget that this is pure JS =) Haha
Would that be negotiable?

**Comment by flauwekeul** [comment]
Just a quick reply because I don't have time: how would you get `orientation` for example from the instance? `Tile.constructor.orientation` is possible, but I think that's even more weird than using `Tile.prototype`.

I don't think hex settings are static. They're shared by all instances, that's why they're in the prototype.

**Comment by israelidanny** [comment]
Yes, you're right: `Tile.constructor.orientation` is also awkward.

But essentially what you have right now is getters that get their scope not even from the class itself but from the scope of the function that created the class. 

I think there are two separate problems here:
- Semantics: You don't really want `Hex` or `Tile` in `distance()`. `distance()` is a mathematical pure function and all it wants is some `HexSettings` the fact that the prototype satisfies that is purely coincidental IMHO. It somehow bothers me - and it's a bit clunkier to work around when consuming the lib. HexSettings are easier to serialize, pass around, store, send over the wire, e.t.c - You can't do any of that with a prototype. *Of course*, we need an easy way to also pass *something* from Tile to make `distance` know what the settings are, but IMHO something like `Tile.getSettings()` would still be a good idea.
- Implementation, how do we implement the right semantics? That's a very mechanical question, it can probably have many possible answers.

Now - if we can agree on the semantics, I think we could come up with solutions. But do we agree on the semantics?

To me as an end user this lib keeps feeling weird, and the source of this weirdness many times is because of passing either `Tile` around, or its' `prototype` to functions that seemingly don't REALLY need it.

**Comment by flauwekeul** [comment]
We agree on the semantics 🙃 I'll need some time to think about this. I've experimented a lot in earlier versions with this and the current solution with the prototype was, then, the best of the worst. But I agree it's still a bit _meh_.

**Comment by flauwekeul** [comment]
A relatively simple solution would be to change the functions that require (part of) the prototype to just require hex settings. It seems these functions are: `pointToCube()`, `offsetToCube()`, `hexToOffset()`, `toCube()` and `distance()` (or did I miss any?).

However, that would only change those functions' signatures, but you'd still have to pass either a hex instance or `Hex.prototype`. I could add a static getter `settings` that can be used like so:

```typescript
class Tile extends Hex {
  get dimensions(): Ellipse {
    return createHexDimensions(30)
  }

  get orientation(): Orientation {
    return Orientation.FLAT
  }
}

Tile.settings
// {
//   dimensions: { xRadius: 30, yRadius: 30 },
//   offset: -1,
//   orientation: "FLAT",
//   origin: {x: 0, y: 0}
// }

distance(Tile.settings, [0, 0], [10, 10])
```

Would this remove some (or all) weirdness in using Honeycomb for you?

**Comment by israelidanny** [comment]
Yes that’d be lovely I think. It’d make the DX a lot more pleasant
