### ISSUE TITLE
grid.neighborsOf

### ISSUE THREAD

**Issue by ggomaeng** [flauwekeul/honeycomb#91]
First, thank you for this amazing project! :) 

Is `grid.neighborsOf` deprecated in v4.0.0?

**Comment by flauwekeul** [comment]
Thanks! 😄 

It's been replaced with [`neighborOf()`](https://abbekeultjes.nl/honeycomb/guide/other-grid-methods.html#neighborof).

**Comment by ggomaeng** [comment]
Wow thank you for such a fast response 💓

Just wondering, does `neighborOf()` return the reference from the grid, or just the hex containing the q, r, s values? 

I am creating custom hexes with custom data inside, but it seems like when I call neighborOf, it doesn't seem to return the binded data associated to the object.

**Comment by ggomaeng** [comment]
To implement `neighborsOf` myself, would something like the code below suffice?

```js
export function neighborsOf(grid, hex) {
  const east = grid.neighborOf(hex, Direction.E);
  const northeast = grid.neighborOf(hex, Direction.NE);
  const southeast = grid.neighborOf(hex, Direction.SE);
  const west = grid.neighborOf(hex, Direction.W);
  const northwest = grid.neighborOf(hex, Direction.NW);
  const southwest = grid.neighborOf(hex, Direction.SW);
  const neighbors = [east, northeast, southeast, west, northwest, southwest].map(({ q, r }) => {
    return grid.getHex([q, r]);
  });
  return neighbors;
}
```

thank you for your input in advance :)

**Comment by ggomaeng** [comment]
Ah I'm glad I could point it out. The previous major version returned the references so I thought I was making a mistake somewhere. Any plans on providing the `neighborsOf` function in the library?

**Comment by flauwekeul** [comment]
The `neighborOf()` (singular) function is already present (both as a standalone function that returns axial coordinates and as a method of `Grid` that returns a hex). If you want the `neighborsOf()` (plural) functionality from v3, you could use the [`ring()` traverser](https://abbekeultjes.nl/honeycomb/guide/traversing-grids.html#ring):
```ts
const neighbors = grid.traverse(ring({ center: [1, 2], radius: 1 }))
```

**Comment by ggomaeng** [comment]
Thank you so much for the pointer! 👍 ❤
