### ISSUE TITLE
Website wrong link

### ISSUE THREAD

**Issue by RobHud** [flauwekeul/honeycomb#92]
There is a wrong link to svgjs.dev in documentation, you have "svgjs.com" which one redirects to poker scam website.
You can found it at this page:
https://abbekeultjes.nl/honeycomb/guide/rendering.html

![image](https://user-images.githubusercontent.com/115623601/198573456-dd1f06a1-37e9-4256-9bff-4112658e1b5e.png)
![image](https://user-images.githubusercontent.com/115623601/198573521-688464f5-405b-4dfe-be18-e9e052947cc7.png)

Sorry for creating an issue about a website here, did not found any other contacts.

**Comment by flauwekeul** [comment]
Thanks for bringing this up. They must have sold their old url or something. I'll fix it right away.
