### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Perlkonig** [flauwekeul/honeycomb#97]
I have a React app that was building and working fine. I upgraded to Honeycomb 4 and updated all my code to the new API, and my tests run fine, but when I try to build my actual app, I get the following error:

```txt
./node_modules/honeycomb-grid/dist/honeycomb-grid.mjs 171:3
Module parse failed: Unexpected token (171:3)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     return -this.q - this.r;
|   }
>   q;
|   r;
|   constructor() {
```

That line number corresponds to the `throw` in the following code:

```js
function nt(r, t) {
  if (S(r) && S(t))
    return r.col === t.col && r.row === t.row;
  if (Object.hasOwn(r, "col") || Object.hasOwn(t, "col"))
    throw new Error(
      `Can't compare coordinates where one are offset coordinates. Either pass two offset coordinates or two axial/cube coordinates. Received: ${JSON.stringify(
        r
      )} and ${JSON.stringify(t)}`
    );
  const e = H(r) ? E(r) : r, n = H(t) ? E(t) : t;
  return e.q === n.q && e.r === n.r;
}
```

I'm tearing my hair out trying to figure out why this is happening. It's React + Webpack + Babel. Any insight would be appreciated. Thanks!

**Comment by flauwekeul** [comment]
The line number (171) corresponds to that line, but the column number (3) does not. Also, I wouldn't know why _that_ line would have an unexpected token.

Maybe your project config expects dependencies to be in commonjs (`module.exports = {}`) syntax while Honeycomb v4 uses native module syntax (`export {}`). Maybe [this](https://stackoverflow.com/a/64907659/660260) helps?

Could you make a reproduction of the problem on [stackblitz](https://stackblitz.com/fork/react) or something similar?

**Comment by Perlkonig** [comment]
Thanks for this. I will see what I can do with this, and if doesn't lead anywhere, I'll see if I can create an isolated reproduction. I appreciate the response.

**Comment by Perlkonig** [comment]
Closing as this is definitely not a "you" issue. Again, I appreciate the response.
